// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKZRiU9cGACpQ0w_hPy3ocVGJZ-qGsHyc',
    appId: '1:344809016028:web:d28d2cb1601e0ce0b20219',
    messagingSenderId: '344809016028',
    projectId: 'saathiapp-b21d8',
    authDomain: 'saathiapp-b21d8.firebaseapp.com',
    storageBucket: 'saathiapp-b21d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uPNGdknqc3zLCpJV1Xr986r2bOFxApw',
    appId: '1:344809016028:android:8f071d2e0d430e8cb20219',
    messagingSenderId: '344809016028',
    projectId: 'saathiapp-b21d8',
    storageBucket: 'saathiapp-b21d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0VeAXLLkEE38z_YN66N9hQgyz2Y-At2c',
    appId: '1:344809016028:ios:abb9cf92801f4fe2b20219',
    messagingSenderId: '344809016028',
    projectId: 'saathiapp-b21d8',
    storageBucket: 'saathiapp-b21d8.appspot.com',
    androidClientId: '344809016028-ho5j4r2pc9haotlek1jpue3i40kch7ut.apps.googleusercontent.com',
    iosClientId: '344809016028-pq2eerd5oshc6qdgf90uqi9o4a2rju2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.saathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0VeAXLLkEE38z_YN66N9hQgyz2Y-At2c',
    appId: '1:344809016028:ios:9f0d9c6f4fa169b2b20219',
    messagingSenderId: '344809016028',
    projectId: 'saathiapp-b21d8',
    storageBucket: 'saathiapp-b21d8.appspot.com',
    androidClientId: '344809016028-ho5j4r2pc9haotlek1jpue3i40kch7ut.apps.googleusercontent.com',
    iosClientId: '344809016028-s3k2cmsadbke7g6nemni786qogat42os.apps.googleusercontent.com',
    iosBundleId: 'com.example.saathi.RunnerTests',
  );
}
